spring.application.name=vms
server.port=${PORT:8080}

app.service-name=${SERVICE_NAME:all}
app.session-timeout-ms=300000
app.default-admin-username=admin
app.default-admin-password=Certified01$
app.default-new-user-password=Match123$

spring.datasource.users.jdbc-url=jdbc:sqlite:data/users.db
spring.datasource.status.jdbc-url=jdbc:sqlite:data/status.db

spring.jackson.serialization.write-dates-as-timestamps=false
spring.mvc.pathmatch.matching-strategy=path_pattern_parser

logging.level.org.springframework.web=INFO
