server {
    listen 80;
    server_name _;

    client_max_body_size 20m;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Cookie $http_cookie;
    proxy_pass_header Set-Cookie;

    # Users microservice
    location /users {
        proxy_pass http://users:8080;
    }
    location /add-user {
        proxy_pass http://users:8080;
    }

    # Admin Panel microservice
    location /admin-panel {
        proxy_pass http://admin:8080;
    }

    # Status microservice
    location /status {
        proxy_pass http://status:8080;
    }

    # Mapview microservice
    location /mapview {
        proxy_pass http://mapview:8080;
    }

    # Core: login, dashboard, venues, profile, logout, home
    location / {
        proxy_pass http://core:8080;
    }
}
